dataflow:
    target: dev
    outputs:
      dev:
        type: duckdb
        path: 'dataflow.duckdb'
        schema: main
        threads: 4
        extensions:
          - httpfs
          - parquet